src/comments/urls.py
from django.conf.urls import url
from .views import  (
    comment_thread
)

urlpatterns = [
    url(r'^(?P<id>\d+)/$', comment_thread, name="thread"),
    # url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete, name="delete"),
]

src/djangoProject/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('posts.urls', namespace="post")),
    url(r'^comments/', include('comments.urls', namespace="comments")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/comments/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.core.urlresolvers import reverse

# from posts.models import Post

# Create your models here.
class CommentManager(models.Manager):
    def all(self):
        qs = super(CommentManager, self).filter(parent=None)
        return qs

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)
        return qs

class Comment(models.Model):

    user        = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    #past        = models.ForeignKey(Post)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    parent = models.ForeignKey("self", null=True, blank=True)

    content     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add = True)

    objects = CommentManager()

    class Meta:
        ordering = ["-timestamp"]

    def __unicode__(self):
        return str(self.user.username)

    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse("comments:thread", kwargs={"id":self.id})

    def children(self): #replies
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

src/posts/models.py
from __future__ import unicode_literals
from django.db.models.signals import pre_save
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils.safestring import mark_safe
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType
from .utils import get_read_time

from markdown_deux import markdown

# Create your models here.
class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
    # filebase, extension = filename.split(".")
    # return "%s/%s.%s" %(instance.id, instance.id, extension)
    return "%s/%s" %(instance.slug, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length = 120)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True,
            height_field = "height_field",
            width_field = "width_field")
    slug = models.SlugField(unique=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now = False, auto_now_add = False)
    content = models.TextField()
    # read_time = models.TimeField(null=True, blank=True)
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now = True, auto_now_add = False)
    timestamp = models.DateTimeField(auto_now = False, auto_now_add = True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post:detail", kwargs={"slug":self.slug})
        # return "/post/%s/" %(self.id)

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        mark_text = markdown(content)
        return mark_safe(mark_text)

    @property
    def comments(self):
        instance = self
        qs =  Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget
from .models import Post

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

src/posts/views.py
try:
    from urllib import quote_plus #python2
except:
    pass
try:
    from urllib.parse import quote_plus #python3
except:
    pass
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages
from django.utils import timezone
from .models import Post
from .forms import PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType
from comments.models import Comment
from comments.forms import CommentForm
from .utils import get_read_time

# Create your views here.

def post_list(request):
    # if request.user.is_authenticated():
    today = timezone.now().date()
    queryset_list = Post.objects.active() #.filter(draft=False).filter(publish__lte=timezone.now()) #.order_by("-timestamp")
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()
    query = request.GET.get("q")
    if query:
        queryset_list = Post.objects.filter(
                        Q(title__icontains=query) |
                        Q(content__icontains=query) |
                        Q(user__first_name__icontains=query) |
                        Q(user__last_name__icontains=query)
                        ).distinct()
    paginator = Paginator(queryset_list, 3) # Show 25 contacts per page
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context={
        "object_list":queryset,
        "title":"Post List",
        "page_request_var": page_request_var,
        "today": today,
    }
    # else:
    #     context = {
    #         "title" : "List"
    #     }
    return render(request, "post_list.html", context)


def post_detail(request, slug):
    # instace = Post.objects.get(id=11)

    instance = get_object_or_404(Post, slug = slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)

    # print (get_read_time(instance.content))
    print (get_read_time(instance.get_markdown()))
    initial_data = {
            "content_type": instance.get_content_type,
            "object_id":instance.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid():
        # print (form.cleaned_data)
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
        new_comment, created = Comment.objects.get_or_create(
                            user = request.user,
                            content_type = content_type,
                            object_id = obj_id,
                            content = content_data,
                            parent = parent_obj,
                        )
        # if created:
        #     print ("YEah")

        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = instance.comments #Comment.objects.filter_by_instance(instance)

    context = {
        "instance":instance,
        "title" : instance.title,
        "share_string": share_string,
        "comments": comments,
        "comment_form": form,
    }
    return render(request, "post_detail.html", context)

def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        print form.cleaned_data.get("title")
        instance.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    # else:
    #     messages.error(request, "Not Successfully Created")

        # if request.method == "POST":
        #     print request.POST.get("content")
    #     print title = request.POST.get("title")
    #     # Post.objects.create(title=title)
    context = {
        "form": form,
    }
    return render(request, "post_form.html", context)

def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "<a href='#'>Item</a> Saved", extra_tags="html_safe")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "instance" : instance,
        "title" : instance.title,
        "form" : form,
    }

    return render(request, "post_form.html", context)

def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully Deleted")
    return redirect("post:list")

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block head_title %}My Blog{% endblock head_title %}
    </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static '/css/base.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
        {% block style %}
        {% endblock style%}
    </style>
    {% block head_extra %} {% endblock head_extra %}
  </head>
  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
      {% include "messages_display.html" %}

      <div class="container">
          {% block content %}

          {% endblock content %}
      </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
     integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
      crossorigin="anonymous">
    </script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
    <script type="text/javaScript">
        $(document).ready(function(){
            $(".content-markdown").each(function(){
                var content = $(this).text()
                // console.log(content)
                var markedContent = marked(content)
                // console.log(markedContent)
                $(this).html(markedContent)
            })
            $(".post-detail-item img").each(function(){
                $(this).addClass("img-responsive");
            })

            var titleInput = $("#id_title");
            // $("#preview-title").text(titleItem.val())

            var contentInput = $("#id_content");
            // $("#preview-content").html(marked(contentItem.val()))
            // console.log(titleItem)

            function setContent(value){
                var markedContent = marked(value)
                $("#preview-content").html(markedContent)
                $("#preview-content img").each(function(){
                    $(this).addClass("img-responsive")
                })
            }
            setContent(contentInput.val())

            contentInput.keyup(function(){
                var newContent = $(this).val()
                setContent(newContent)
            })

            function setTitle(value){
                $("#preview-title").text(value)
            }
            setTitle(titleInput.val())

            titleInput.keyup(function(){
                var newTitle = $(this).val()
                setTitle(newTitle)
            })

            $(".comment-reply-btn").click(function(event){
                event.preventDefault();
                $(this).parent().next(".comment-reply").fadeToggle();
            })
        })
    </script>
  </body>
</html>

src/templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block head_title %}
    {{instance.title}} | {{block.super}}
{% endblock head_title %}

{{object}}

{% block content %}
{{object}}
<div class="col-sm-6 col-sm-offset-3">
        <p>{{comment.content}}</p>
        <footer>
            via {{comment.user}} | {{comment.timestamp|timesince}} ago |
            {% if comment.children.count > 0 %}
             {{comment.children.count}} Comment{%if comment.children.count > 1 %}s {% endif %}
            {% endif %}
        </footer>
        <hr>
        <div class="comment-reply">
            {% for comment_child in comment.children %}
            <blockquote>
            <p>{{comment_child.content}}</p>
            <footer>via {{comment_child.user}} | {{comment_child.timestamp|timesince}} ago</footer>
            </blockquote>
            {% endfor %}

            <form class="" action="." method="post"> {% csrf_token %}
                {{ form |crispy}}
                <input type="hidden" name="parent_id" value="{{comment.id}}">
                <input type="submit" name="" value="Reply" class="btn btn-default">
            </form>
        </div>

</div>
{% endblock content %}

src/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block head_title %}
    {{instance.title}} | {{block.super}}
{% endblock head_title %}

<!-- /*<style>
    {% block style %}
        h1{
            color: #777777;
        }
    {% endblock style%}
</style>*/ -->

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
    {% if instance.image %}
        <img src="{{instance.image.url}}" alt="" class="img-responsive">
    {% endif %}
    <h1>
        {{title}} <small>{% if instance.draft %}<span style="color:red">Draft </span>
            {% endif %}{{instance.publish}}</small>
    </h1>
    <!-- <p>Read Time: {% if instance.read_time|time:"i" <= "01" %} < 1 minute {% elif instance.read_time|time:"i" <= "10" %} < 10 minutes {% else %} {{instance.read_time|time:"i"}} minutes{% endif %}</p> -->
    <p>Read Time: {% if instance.read_time <= 1 %} < 1 Minute {% elif instance.read_time <= 10 %} < 10 Minutes {% else %} {{instance.read_time}} Minutes{% endif %}</p>
    <p>
        {% if instance.user.get_full_name %}
            Author: {{instance.user.get_full_name}}
        {% else %}
            Author: {{instance.user}}
        {% endif %}
    </p>

    <p>

        <div class="fb-like" data-href={{request.build_absolute_uri}}
        data-layout="standard" data-action="like" data-size="small"
        data-show-faces="true" data-share="true"></div>

    </p>
    <!-- {{share_string}} <br /> -->
    <!-- {{instance.content |truncatechars:80| urlify}}<br /> -->
    <p>
        <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
        Facebook
        </a>

        <a href="https://twitter.com/home?status={{instance.content |truncatechars:80| urlify}}%20{{request.build_absolute_uri}}">
        Twitter
        </a>

        <a href='https://plus.google.com/share?url={{request.build_absolute_uri}}'>Google-Plus</a>

        <a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}
        &title={{instance.title}}&summary={{share_string}}&source={{request.build_absolute_uri}}">
        Linkedin
        </a>

        <a href="http://www.reddit.com/submit?url={{request.build_absolute_uri}}
        &title={{share_string}}.">Reddit</a>
    </p>

    <hr />
    <div class="row">
        <div class="col-sm-12">
            <div class="post-detail-item img">{{instance.get_markdown}}</div>
        <br />
        <hr />
        <!-- {{instance.comments.all}} -->
        <div class="">
            <!-- {{instance.comment_set.all}} -->
            <p class="lead">Comments</p>
            <form class="" action="." method="post"> {% csrf_token %}
                {{comment_form |crispy}}
                <input type="submit" name="" value="Post Comment" class="btn btn-default">

            </form>
            <hr />
            {% for comment in comments %}

                <blockquote>
                    <p>{{comment.content}}</p>
                    <footer>
                        via {{comment.user}} | {{comment.timestamp|timesince}} ago |
                        {% if comment.children.count > 0 %}
                         {{comment.children.count}} Comment{%if comment.children.count > 1 %}s {% endif %}
                        |{% endif %}
                        <a class="comment-reply-btn" href="#">Reply</a> |
                        <a href="{{comment.get_absolute_url}}">Thread</a>
                    </footer>
                    <div class="comment-reply" style="display:none;">
                        {% for comment_child in comment.children %}
                        <blockquote>
                        <p>{{comment_child.content}}</p>
                        <footer>via {{comment_child.user}} | {{comment_child.timestamp|timesince}} ago</footer>
                        </blockquote>
                        {% endfor %}

                        <form class="" action="." method="post"> {% csrf_token %}
                            {{comment_form |crispy}}
                            <input type="hidden" name="parent_id" value="{{comment.id}}">
                            <input type="submit" name="" value="Reply" class="btn btn-default">
                        </form>
                    </div>
                </blockquote>
                <hr />
            {% endfor%}
        <!-- </div>
    <div class="row">
        <div class="col-sm-12" "col-sm-offset-2">
            <div class="fb-comments" data-href={{request.build_absolute_uri}} data-numposts="5"></div>
        </div> -->
        </div>


    <!-- {{request.build_absolute_uri}} -->



</div>
{% endblock content %}

src/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
    {{form.media}}
{% endblock head_extra%}
{% block content %}
<!-- {{block.super}} to retrive parent template content -->
<div class="col-sm-6">
    <h1>Preview</h1>
    <hr>
    <div class="content-preview">
        <h3 id="preview-title"></h3>
        <p id="preview-content"></p>
    </div>
</div>
<div class="col-sm-6">
      <h1>Form</h1>
      <hr>
      <form method = "POST" action="" enctype="multipart/form-data"> {% csrf_token %}
          {{form|crispy}}
          <input type="submit" class="btn-primary" value="Create Post">
      </form>
</div>
{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}
{% block content %}

          <!-- {{object_list}} -->

        <div class="col-sm-6 col-sm-offset-3">
            <h1>{{title}}</h1>

            <p>
            <form class="row" action="" method="GET">
                <div class="col-sm-6">
                    <div class="input-group">
                    <!-- <div class="form-group"> -->
                        <input class="form-control" type="text" name="q" value="{{request.GET.q}}" placeholder="Search post">
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </button>
                        </span>
                        <!-- <input butt type="submit" name="" value="Search"> -->
                    <!-- </div> -->
                    </div>
                </div>
            </form>
            </p>

        {% for obj in object_list %}
        <!-- <div class="col-sm-6">

            {{obj.id}} &nbsp;
            {% url "post:detail" slug=obj.slug %}
            <a href={{obj.get_absolute_url}}>{{obj.title}}</a> </br>
            {{obj.content | linebreaks | truncatechars:120}}</br>
            {{obj.timestamp}}</br>
            {{obj.updated}}</br></br>
        </div> -->
            <div class="row">
              <div class="col-sm-12">
                <div class="thumbnail">
                    {% if obj.image %}
                        <img src="{{obj.image.url}}" alt="" class="img-responsive">
                    {% endif %}
                  <div class="caption post-detail-item img">
                     {% if obj.draft %}<h3>Staff Only: Draft</h3>{% endif %}
                     {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
                    <h3><a href="{{obj.get_absolute_url}}">{{obj.title}}</a><small> {{obj.publish | timesince}}</small></h3>
                    <p>
                        {% if obj.user.get_full_name %}
                            Author: {{obj.user.get_full_name}}
                        {% else %}
                            Author: {{obj.user}}
                        {% endif %}
                    </p>
                    {{obj.get_markdown| truncatechars_html:50 }}
                    <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">View</a>
                  </div>
                </div>
              </div>
              <hr>
          </div>

            <!-- {% cycle "" "<div class='col-sm-12'><hr></div></div> <div class='row'>" %} -->
        {% endfor %}

        <div class="pagination">
            <span class="step-links">
                {% if object_list.has_previous %}
                    <a href="?{{page_request_var}}={{ object_list.previous_page_number }}{% if request.GET.q %} &q={{request.GET.q}} {% endif %}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                </span>

                {% if object_list.has_next %}
                    <a href="?{{page_request_var}}={{ object_list.next_page_number }}{% if request.GET.q %} &q={{request.GET.q}} {% endif %}">next</a>
                {% endif %}
            </span>
        </div>

        </div>

{% endblock content %}